Add support for -f|--force and -y|--yes

diff --git a/pa b/pa
--- a/pa
+++ b/pa
@@ -2,13 +2,25 @@
 #
 # pa - a simple password manager based on age
 
+FORCE=""
+YES=""
+
 : "${XDG_DATA_HOME:=$HOME/.local/share}"
 : "${PA_DIR:=$XDG_DATA_HOME/pa/passwords}"
 : "${PA_LENGTH:=20}"
 : "${PA_PATTERN:=_A-Z-a-z-0-9}"
 
+check_bounds() {
+    glob "$1" '*../*' && die "Category went out of bounds"
+    glob "$1" '/*' && die "Category can't start with '/'"
+    glob "$1" '*/*' && { mkdir -p "${1%/*}" || die "Couldn't create category '${1%/*}'"; }
+}
+
 pw_add() {
-    name=$1
+    local name="$1"
+    [ -z "$name" ] && die "Missing [name] argument"
+    [ -z "$FORCE" ] && [ -f "$name.age" ] && die "Password '$name' already exists"
+    check_bounds "$name"
 
     if yn "Generate a password?"; then
         pass=$(rand_chars "$PA_LENGTH" "$PA_PATTERN")
@@ -44,10 +56,11 @@ pw_add() {
 }
 
 pw_edit() {
-    name=$1
-
-    [ -f "$name.age" ] ||
-        die "Couldn't access $name"
+    local name="$1"
+    [ -z "$name" ] && die "Missing [name] argument"
+    [ ! -f "$name.age" ] && [ -n "$FORCE" ] && age --encrypt -R "$recipients_file" -o "$name.age" < /dev/null
+    [ ! -f "$name.age" ] && die "Password '$name' doesn't exist"
+    check_bounds "$name"
 
     # Prefer /dev/shm because it's an in-memory
     # space that we can use to store data without
@@ -83,6 +96,11 @@ pw_edit() {
 }
 
 pw_del() {
+    local name="$1"
+    [ -z "$name" ] && die "Missing [name] argument"
+    [ ! -f "$name.age" ] && return 0;
+    check_bounds "$name"
+
     yn "Delete pass file '$1'?" && {
         rm -f "$1.age"
 
@@ -94,8 +112,13 @@ pw_del() {
 }
 
 pw_show() {
-    age --decrypt -i "$identities_file" "$1.age" ||
-        die "Couldn't decrypt $1.age"
+    local name="$1"
+    [ -z "$name" ] && die "Missing [name] argument"
+    [ ! -f "$name.age" ] && die "Password '$name' doesn't exist"
+    check_bounds "$name"
+
+    age --decrypt -i "$identities_file" "$name.age" ||
+        die "Couldn't decrypt $name.age"
 }
 
 pw_list() {
@@ -122,6 +145,7 @@ rand_chars() {
 }
 
 yn() {
+    [ -n "$YES" ] && return 0;
     printf '%s [y/N]: ' "$1"
 
     # Enable raw input to allow for a single byte to be read from
@@ -186,6 +210,10 @@ usage() {
     [l]ist        - List all entries.
     [s]how [name] - Show password for an entry.
 
+  switches:
+    -f, --force   - Overwrite existing files
+    -y, --yes     - Answer yes to questions
+
   env vars:
     Password length:   export PA_LENGTH=$PA_LENGTH
     Password pattern:  export PA_PATTERN=$PA_PATTERN
@@ -219,24 +247,6 @@ main() {
     command -v age-keygen >/dev/null 2>&1 ||
         die "age-keygen not found, install per https://github.com/FiloSottile/age"
 
-    glob "$1" '[ades]*' && [ -z "$2" ] &&
-        die "Missing [name] argument"
-
-    glob "$1" '[des]*' && [ ! -f "$2.age" ] &&
-        die "Password '$2' doesn't exist"
-
-    glob "$1" 'a*' && [ -f "$2.age" ] &&
-        die "Password '$2' already exists"
-
-    glob "$2" '*/*' && glob "$2" '*../*' &&
-        die "Category went out of bounds"
-
-    glob "$2" '/*' &&
-        die "Category can't start with '/'"
-
-    glob "$2" '*/*' && { mkdir -p "${2%/*}" ||
-        die "Couldn't create category '${2%/*}'"; }
-
     # Restrict permissions of any new files to
     # only the current user.
     umask 077
@@ -255,14 +265,20 @@ main() {
     # state on exit or Ctrl+C.
     [ -t 1 ] && trap 'stty echo icanon' INT EXIT
 
-    case $1 in
-    a*) pw_add "$2" ;;
-    d*) pw_del "$2" ;;
-    e*) pw_edit "$2" ;;
-    l*) pw_list ;;
-    s*) pw_show "$2" ;;
-    *) usage ;;
-    esac
+    local cmd="usage"
+    local -a unparsed
+    while [ -n "$*" ]; do case "$1" in
+    a*) cmd="pw_add" ; shift ;;
+    d*) cmd="pw_del" ; shift ;;
+    e*) cmd="pw_edit" ; shift ;;
+    l*) cmd="pw_list" ; shift ;;
+    s*) cmd="pw_show" ; shift ;;
+    -f|--force) FORCE=1; shift ;;
+    -y|--yes) YES=1; shift ;;
+    *) unparsed+=("$1"); shift ;;
+    esac done
+
+    "$cmd" "${unparsed[@]}"
 }
 
 # Ensure that debug mode is never enabled to
